{{- if and .Values.immich.apiKey (not .Values.immich.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postcards.fullname" . }}-immich
  labels:
    {{- include "postcards.labels" . | nindent 4 }}
type: Opaque
stringData:
  IMMICH_API_KEY: {{ .Values.immich.apiKey | quote }}
---
{{- end }}
{{- if and (or .Values.pcc.username .Values.pcc.password) (not .Values.pcc.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postcards.fullname" . }}-pcc
  labels:
    {{- include "postcards.labels" . | nindent 4 }}
type: Opaque
stringData:
  PCD_USERNAME: {{ .Values.pcc.username | quote }}
  PCD_PASSWORD: {{ .Values.pcc.password | quote }}
---
{{- end }}
{{- if and .Values.token.initialTokenJson (not .Values.token.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postcards.fullname" . }}-token
  labels:
    {{- include "postcards.labels" . | nindent 4 }}
type: Opaque
stringData:
  token.json: {{ .Values.token.initialTokenJson | quote }}
{{- end }}
